name = "card-studio"
compatibility_date = "2024-11-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
BITABLE_BASE_TOKEN = "BQ3gbOvjPa8tG9sAeRycCJSInrh"
BITABLE_TABLE_GRAPHS = "tblYWFt0cNPvIKb8"
BITABLE_TABLE_COPY = "tblRSEX8K3mvKpix"
